# Based on https://colinsalmcorner.com/consuming-environment-secrets-in-reusable-workflows/

name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev'
  
jobs:
  deploy_dev:
    name: Deploy to DEV
    if: github.ref == 'refs/heads/dev'
    uses: palaszhubert/gha-test-reusable-workflow-deployment/.github/workflows/reusable-deployment.yml@main
    with:
      environment: DEV
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}
      
  deploy_prod:
    name: Deploy to PROD
    if: github.ref == 'refs/heads/main'
    uses: palaszhubert/gha-test-reusable-workflow-deployment/.github/workflows/reusable-deployment.yml@main
    with:
      environment: PROD
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}